frameworkVersion: '3'
service: my-chat-lambda
app: backend
useDotenv: true
provider:
  name: aws
  runtime: nodejs20.x
  deploymentMethod: direct
  versionFunctions: false
  iam:
    role: DefaultRole
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:3000
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowedHeaders:
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
      allowCredentials: true
  stage: dev-1
  tags:
    Service: ${self:service}
    Environment: ${env:STAGE, "dev"}
  stackTags:
    Service: ${self:service}
    Environment: ${env:STAGE, "dev"}
  region: ${opt:region, "ap-northeast-2"}
  stackName: ${self:service}-${env:STAGE, "dev"}-${env:VER, "1"}-serverless
  timeout: 29
  environment:
    service: ${self:service}
    version: ${env:VER, "1"}
    stage: ${env:STAGE, "dev"}
    region: ${opt:region, "ap-northeast-2"}
    app: ${self:app}
    api_gateway_id:
      Ref: HttpApi
    socket_api_gateway_id:
      Ref: WebsocketsApi
  deploymentBucket:
    name: ${aws:accountId}-serverless-deploys
    maxPreviousDeploymentArtifacts: 5
    blockPublicAccess: true
  deploymentPrefix: ${self:service}-${env:STAGE, "dev"}-${env:VER, "1"}-backend
plugins:
  - serverless-deployment-bucket
resources:
  Resources:
    DefaultRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:app}-${env:STAGE, "dev"}-${env:VER, "1"}-DefaultLambdaExcutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/AmazonS3FullAccess
          - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
        Policies:
          - PolicyName: myPolicyName
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:*
                    - ssm:*
                    - execute-api:*
                    - sqs:*
                  Resource: '*'
    chatappChatRoomList:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${env:STAGE, "dev"}-chat-room-list-${env:VER, "1"}
        AttributeDefinitions:
          - AttributeName: room_id
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S
        KeySchema:
          - AttributeName: room_id
            KeyType: HASH
          - AttributeName: created_at
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    chatappChatMessages:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${env:STAGE, "dev"}-chat-messages-${env:VER, "1"}
        AttributeDefinitions:
          - AttributeName: room_id
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: 'N'
        KeySchema:
          - AttributeName: room_id
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
    chatappChatUserlist:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${env:STAGE, "dev"}-chat-userlist-${env:VER, "1"}
        AttributeDefinitions:
          - AttributeName: connection_id
            AttributeType: S
          - AttributeName: room_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
        KeySchema:
          - AttributeName: connection_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: room_id-user_id-index
            KeySchema:
              - AttributeName: room_id
                KeyType: HASH
              - AttributeName: user_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
  Outputs:
    ServerlessDeploymentBucketName:
      Export:
        Name: ${self:provider.stackName}-ServiceEndpoint
      Value: ${self:provider.stackName}-ServiceEndpoint
    HttpApiUrl:
      Export:
        Name: ${self:provider.stackName}-HttpApiUrl
    HttpApiId:
      Export:
        Name: ${self:provider.stackName}-HttpApiId
custom: null
functions:
  chat_createRoom:
    name: ${self:service}_dev_1_chat_createRoom
    handler: src/lambda/chat/createRoom.handler
    events:
      - httpApi:
          path: /dev/chat/createRoom
          method: post
  chat_get:
    name: ${self:service}_dev_1_chat_get
    handler: src/lambda/chat/get.handler
    events:
      - httpApi:
          path: /dev/chat
          method: get
  chat_getRoom:
    name: ${self:service}_dev_1_chat_getRoom
    handler: src/lambda/chat/getRoom.handler
    events:
      - httpApi:
          path: /dev/chatRoom
          method: get
  chat_handleStream:
    name: ${self:service}_dev_1_chat_handleStream
    handler: src/lambda/chat/handleStream.handler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - chatappChatMessages
              - StreamArn
    timeout: 100
  chat_onConnect:
    name: ${self:service}_dev_1_chat_onConnect
    handler: src/lambda/chat/onConnect.handler
    events:
      - websocket:
          route: $connect
  chat_onDefault:
    name: ${self:service}_dev_1_chat_onDefault
    handler: src/lambda/chat/onDefault.handler
    events:
      - websocket:
          route: $default
  chat_onDisconnect:
    name: ${self:service}_dev_1_chat_onDisconnect
    handler: src/lambda/chat/onDisconnect.handler
    events:
      - websocket:
          route: $disconnect
  chat_put:
    name: ${self:service}_dev_1_chat_put
    handler: src/lambda/chat/put.handler
    events:
      - httpApi:
          path: /dev/chat
          method: put
