service: serverless-image-upload

frameworkVersion: '3'

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-ignore
  - serverless-dotenv-plugin

apiGateway:
  binaryMediaTypes:
    - 'multipart/form-data'
    - 'image/*'

provider:
  name: aws
  region: ap-northeast-2
  runtime: nodejs20.x

functions:
  api:
    handler: src/lambda.handler
    events:
      - http:
          method: any
          path: /{proxy+}
